# Generated by Django 2.1.3 on 2018-11-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='coefficient',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
